# Generated by Django 3.1.4 on 2021-02-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201227_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='height',
            field=models.IntegerField(blank=True, default=176, max_length=10),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='weight',
            field=models.CharField(blank=True, default=65, max_length=10),
        ),
    ]
