# Generated by Django 3.1.4 on 2021-02-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210203_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='height',
            field=models.IntegerField(blank=True, default=176),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='weight',
            field=models.IntegerField(blank=True, default=65),
        ),
    ]
