# Generated by Django 3.1.4 on 2021-03-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('des', models.CharField(blank=True, max_length=500, null=True)),
                ('is_enrolled', models.BooleanField(blank=True, default=False, null=True)),
                ('buyLink', models.CharField(blank=True, max_length=120, null=True)),
                ('img_card', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_first', models.ImageField(blank=True, null=True, upload_to='')),
                ('test_l1', models.CharField(blank=True, max_length=120, null=True)),
                ('test_l2', models.CharField(blank=True, max_length=120, null=True)),
                ('test_l3', models.CharField(blank=True, max_length=120, null=True)),
                ('test_n1', models.CharField(blank=True, max_length=120, null=True)),
                ('test_n2', models.CharField(blank=True, max_length=120, null=True)),
                ('test_n3', models.CharField(blank=True, max_length=120, null=True)),
                ('test_d1', models.CharField(blank=True, max_length=450, null=True)),
                ('test_d2', models.CharField(blank=True, max_length=450, null=True)),
                ('test_d3', models.CharField(blank=True, max_length=450, null=True)),
                ('feat_l', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
