# Generated by Django 3.1.4 on 2021-01-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201221_2257'),
        ('services', '0003_service_slug'),
    ]

    operations = [
    ]
