# Generated by Django 3.1.4 on 2021-01-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_merge_20210106_1859'),
        ('services', '0004_merge_20210106_1823'),
    ]

    operations = [
    ]
