# Generated by Django 3.1.4 on 2021-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_merge_20210111_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='img_main',
            new_name='thumb1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_enrolled',
        ),
        migrations.AddField(
            model_name='service',
            name='feat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='test1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='test2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='test3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='thumb2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='thumb3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
