# Generated by Django 3.1.4 on 2021-03-27 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('razorpay_payment_id', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('oder_date', models.DateTimeField(default=datetime.datetime(2021, 3, 27, 9, 51, 20, 564149))),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2021, 4, 26, 9, 51, 20, 564149))),
            ],
        ),
    ]
