# Generated by Django 3.1.4 on 2021-02-03 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210203_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 17, 9, 32, 889454)),
        ),
        migrations.AlterField(
            model_name='order',
            name='oder_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 17, 9, 32, 889454)),
        ),
    ]
