# Generated by Django 3.1.4 on 2021-03-27 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210327_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 13, 2, 28, 260932)),
        ),
        migrations.AlterField(
            model_name='order',
            name='oder_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 13, 2, 28, 260932)),
        ),
    ]
