# Generated by Django 3.1.4 on 2021-03-16 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210314_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 23, 31, 5, 455886)),
        ),
        migrations.AlterField(
            model_name='order',
            name='oder_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 23, 31, 5, 455886)),
        ),
    ]
