# Generated by Django 3.1.4 on 2021-03-12 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(choices=[('SPORT', 'SPORT'), ('MUSIC', 'MUSIC'), ('FOOD', 'FOOD'), ('FITNESS', 'FITNESS')], max_length=20)),
                ('blog_image', models.ImageField(upload_to='blog_images')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_content', models.TextField()),
                ('blog_tags', multiselectfield.db.fields.MultiSelectField(choices=[('#SPORT', 'SPORT'), ('#TRAVEL', 'TRAVEL'), ('#FOOD', 'FOOD'), ('#FITNESS', 'FITNESS')], max_length=29)),
                ('blog_datetime', models.DateTimeField(auto_now_add=True)),
                ('blog_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_blog',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('comment_datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('comment_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_blog_comment',
            },
        ),
    ]
