# Generated by Django 3.1.4 on 2021-03-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['blog_datetime']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_tags',
        ),
    ]
