# Generated by Django 3.1.4 on 2021-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210314_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment_user',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
